name: CI

on:
  push:

jobs:
  job1:
    runs-on: windows-latest  # Change from ubuntu-latest to windows-latest
    
    name: Build and Test

    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (still uses actions/setup-java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'



      # Step 4: Build and test the project using Gradle
      - name: Build and test
        working-directory: RentalService  # Assuming your project is in this folder
        run: |
          # Set the shell for Windows (PowerShell or Command Prompt)
          .\gradlew build  # For Windows, just use the Gradle wrapper directly

      # Step 5: Build Docker images (Ensure Docker is installed and running on GitHub Actions)
      - name: Docker images
        working-directory: RentalService
        run: |
          docker build -t rentalservice .
          docker images
